name: Tests
on:
    push:
        branches: "main"

jobs:
    sample_tests:
        runs-on: ubuntu-latest

        steps:
            # Checkout test && existence of tag with default prefix check
            - name: Version checkout
              uses: Clovis1444/GetVersion@main
              id: version_checkout
              with:
                  file_to_read: "tests/sample to checkout/version.txt"
                  line_pattern: "version="
                  checkout: true

            - uses: nick-fields/assert-action@v2
              with:
                  expected: "0.0.12"
                  actual: ${{ steps.version_checkout.outputs.project_version }}

            - uses: nick-fields/assert-action@v2
              with:
                  expected: "true"
                  actual: ${{ steps.version_checkout.outputs.exists }}

            # Checkout from other repo && tag existence in other repo
            - name: Other repo checkout
              uses: Clovis1444/GetVersion@main
              id: repo_checkout
              with:
                  file_to_read: manifest.json
                  line_pattern: '"version":'
                  checkout: true
                  repo: Clovis1444/KPFB-firefox

            - uses: nick-fields/assert-action@v2
              with:
                  expected: "0.0.3"
                  actual: ${{ steps.repo_checkout.outputs.project_version }}

            - uses: nick-fields/assert-action@v2
              with:
                  expected: "true"
                  actual: ${{ steps.repo_checkout.outputs.exists }}

            #
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  sparse-checkout: tests/samples

            # CMake file text
            - name: CMakeLists.txt
              uses: Clovis1444/GetVersion@main
              id: CMakeLists
              with:
                  file_to_read: tests/samples/CMakeLists.txt
                  line_pattern: "project(init"

            - uses: nick-fields/assert-action@v2
              with:
                  expected: "0.1.0"
                  actual: ${{ steps.CMakeLists.outputs.project_version }}

            # version_pattern with postfix
            - name: manifest.json
              uses: Clovis1444/GetVersion@main
              id: manifest
              with:
                  file_to_read: tests/samples/manifest.json
                  line_pattern: '"version":'
                  version_pattern: '[0-9]\+\.[0-9]\+\.[0-9]\+-[a-z]\+'

            - uses: nick-fields/assert-action@v2
              with:
                  expected: "2.0.6-beta"
                  actual: ${{ steps.manifest.outputs.project_version }}

            # version_patter with four-part version number
            - name: package.json
              uses: Clovis1444/GetVersion@main
              id: package
              with:
                  file_to_read: tests/samples/package.json
                  line_pattern: '"version":'
                  version_pattern: '[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+'

            - uses: nick-fields/assert-action@v2
              with:
                  expected: "228.0.1.12"
                  actual: ${{ steps.package.outputs.project_version }}
